### ISSUE TITLE
Index out of bounds! Error when run example code block 

### ISSUE THREAD

**Issue by mrvgao** [drageelr/manim-data-structures#12]
## Description of the bug

When I run the example code black. I met the `Exception: Index out of bounds!`

## Steps to reproduce

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
I just past-and-copy the example code 
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/6982171/212200274-5e41fda0-d8af-4667-9a80-8a5d730f7b06.png">

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
Python 3.10.8
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/6982171/212200141-9b83648b-b9fe-4895-9981-3e4ab693d058.png">

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

```
</details>

**Comment by drageelr** [comment]
Please share the code to reproduce the bug.

**Comment by drageelr** [comment]
Just figured that you were referring to the example code block in the README.md file. That example is outdated, it would work on versions <= 0.1.5, since from v0.1.6 onward the first argument to all data structures in this package needs the `Scene` object as the first argument. If you want to have a look at other examples please visit the [official documentation](https://manim-data-structures.readthedocs.io/)'s **Animating Arrays** guide or the **Example Gallery**.

Will update the README.md in the next release.
